[package]
name = "android_homework_organizer_mk2"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.11.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
termion = "4.0.5"
